version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Use the node_modules from the container, not the host
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  node_modules:
