name: Deploy Insurance Sales Agent (Cloud Run)

on:
  push:
    branches: [ "main" ]
    paths:
      - "agents/insurance_sales_agent/**"
      - "agents/shared/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (source)
        run: |
          gcloud run deploy insurance-sales-agent \
            --source ./agents/insurance_sales_agent/backend \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --set-env-vars="ETHOS_URL=${{ secrets.ETHOS_URL }},BACKNINE_URL=${{ secrets.BACKNINE_URL }},EMAIL_RECEIVE=${{ secrets.EMAIL_RECEIVE }},AI_MODEL=${{ secrets.AI_MODEL }},OLLAMA_HOST=${{ secrets.OLLAMA_HOST }}" \
            --set-secrets=OPENAI_API_KEY=projects/${{ secrets.GCP_PROJECT }}/secrets/OPENAI_API_KEY:latest,SENDGRID_API_KEY=projects/${{ secrets.GCP_PROJECT }}/secrets/SENDGRID_API_KEY:latest \
            --memory=1Gi
